name: Java CI with Maven

on:
  push:
    branches: [ Graph ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.kthcloud.com
          username: robot$data-ht2022+shared
          password: Fupabaxo11
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.kthcloud.com/data-ht2022/data1-api6:latest
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
